window.addEventListener('load',()=>{const modulos=[];const swopCapa=document.querySelectorAll('.swop_capa');swopCapa.forEach(function(modulo,i){if(!['absolute','fixed'].includes(window.getComputedStyle(modulo.firstElementChild).position)){modulos.push(modulo);const atual=modulo.firstElementChild;const anterior=modulos[modulos.length-2]&&modulos[modulos.length-2].firstElementChild;if(anterior&&window.getComputedStyle(anterior,null).getPropertyValue('background')!=window.getComputedStyle(atual,null).getPropertyValue('background')){anterior&&anterior.classList.add("pdb");atual.classList.add("pdt")}}})});function swGetParametrosModuloCapa(modulo){try{const input=modulo.querySelector('input.parametros_modulo_capa');const parametros=swJsonInput(input);return parametros}catch(error){return!1}}
function swLayoutModuloCapa(param,callback,timeout){try{if(!param.elemento){throw 'Elemento inexistente'}
if(!param.parametrosModuloCapa){throw 'Parâmetros do módulo indefinidos'}
const multiplos=parseInt(param.multiplos?param.multiplos:param.parametrosModuloCapa.multiplos);const destaque=parseInt(param.destaque?param.destaque:param.parametrosModuloCapa.destaque);const exibicaoItem=param.exibicao_item?param.exibicao_item:param.parametrosModuloCapa.exibicao_item;const contListagem=param.elemento.querySelector('.p_cont_listagem');if(!contListagem){throw 'Elemento "p_cont_listagem" não encontrado.'}['li','lr0','lr1','lr2','lr3','lr4','lr5','lr6','lr7','lr8','lr9','lr10'].forEach(classe=>{contListagem.classList.remove(classe)});const qtdeItens=param.elemento.querySelectorAll('.p_cont_listagem > .p_item').length;if(qtdeItens){if(multiplos){contListagem.classList.add('m'+multiplos)
contListagem.classList.add('lr'+(qtdeItens%multiplos))}
if(destaque===qtdeItens){param.elemento.classList.add('l'+destaque)}
if(qtdeItens%2===1){contListagem.classList.add('li')}
if(exibicaoItem){contListagem.classList.add('exibicao_'+exibicaoItem)}
contListagem.setAttribute('data-itens',qtdeItens)}
if(param.parametrosModuloCapa.disposicao_invertida){contListagem.classList.add('disposicao_invertida')}else{contListagem.classList.remove('disposicao_invertida')}
if(param.parametrosModuloCapa.exibicao_mobile){swExibicaoMobile(param,callback,timeout)}}catch(error){console.error('SW Layout Módulo:',error)}}
function swExibicaoMobile(param,callback,timeout){try{if(typeof param===typeof undefined){throw 'Parâmetros indefinidos'}
if(typeof param.parametrosModuloCapa===typeof undefined){throw 'Parâmetros do módulo da capa indefinidos'}
if(typeof param.elemento===typeof undefined){throw 'Parâmetro "elemento" indefinido'}
if(typeof param.elemento===typeof String()){param.elemento=document.querySelector(param.elemento)}
const contElemento=param.elemento&&param.elemento.querySelector('.p_cont_listagem');if(!contElemento){throw 'Elemento ".p_cont_listagem" não encontrado.'}
if(typeof param.media===typeof undefined){param.media=(param.parametrosModuloCapa.flutuante===!1)?window.innerWidth:800}
if(window.innerWidth<=param.media){if(param.parametrosModuloCapa.exibicao_mobile==='rolagem'){contElemento.classList.add('p_rolagem')}else if(param.parametrosModuloCapa.exibicao_mobile&&param.parametrosModuloCapa.exibicao_mobile!=='false'){contElemento.classList.replace('p_cont_listagem','p_slide');const parametrosSlideModulo={elemento:contElemento,setas:!1,rotacionar:!1,thumbnail:!1,};param.parametrosModuloCapa.exibicao_mobile.split(',').forEach(p=>{switch(p){case 'setas':parametrosSlideModulo.setas=!0;break;case 'rotacionar':parametrosSlideModulo.rotacionar=5;break;case 'thumbnail':parametrosSlideModulo.thumbnail=!0;break}});sw_slider(parametrosSlideModulo,callback,timeout)}}}catch(error){console.error('SW Exibição Mobile:',error)}}
function swSlideModulos(param,callback,timeout){try{if(typeof param===typeof undefined){throw 'Parâmetros indefinidos'}
if(!param.parametrosModuloCapa){throw 'Parâmetros do módulo indefinidos'}
if(!param.elemento){throw 'Módulo indefinido'}
const itens=param.elemento.querySelectorAll('.p_cont_listagem > .p_item');if(!itens){throw 'Não foram encontrados os elementos "p_item" dentro da classe "p_cont_listagem"'}
const listaItens=[...itens];const qtdeFixos=(window.innerWidth>1000)?param.parametrosModuloCapa.fixos:param.parametrosModuloCapa.fixos_mobile;if(qtdeFixos!=listaItens.length){const areaSlide=document.createElement('div');areaSlide.className="p_area_slide";areaSlide.append(document.createElement('div'));areaSlide.querySelector('div').className='p_slide';param.elemento.querySelector('.p_cont_modulo_slide .p_area_listagem').append(areaSlide)}
if(param.parametrosModuloCapa.slide_antecede_fixos===!0){param.elemento.querySelector('.p_area_listagem').insertBefore(param.elemento.querySelector('.p_area_listagem').children[1],param.elemento.querySelector('.p_area_listagem').children[0]);param.elemento.querySelector('.p_slide').append(...listaItens.slice(0,listaItens.length-qtdeFixos))}else{param.elemento.querySelector('.p_slide').append(...listaItens.slice(qtdeFixos))}
param.elemento.querySelector('.p_slide').setAttribute('data-itens',param.elemento.querySelectorAll('.p_slide .p_item').length);if(param.parametrosModuloCapa.exibicao_item_slide){param.elemento.querySelector('.p_slide').classList.add('exibicao_'+param.parametrosModuloCapa.exibicao_item_slide)}
if(param.parametrosModuloCapa.barra_rolagem===!0){param.elemento.querySelector('.p_slide').classList.replace('p_slide','p_rolagem');param.elemento.querySelector('.p_rolagem').classList.add('m'+param.parametrosModuloCapa.multiplos_slide)}else{const parametrosSlide={}
parametrosSlide.elemento=param.elemento.querySelector('.p_slide');const minWidth=(parametrosSlide.elemento.getBoundingClientRect().width/param.parametrosModuloCapa.multiplos_slide)*.95;parametrosSlide.minwidth=(minWidth>200)?minWidth:200;parametrosSlide.rotacionar=param.parametrosModuloCapa.rotacionar;parametrosSlide.setas=param.parametrosModuloCapa.setas;parametrosSlide.thumbnail=param.parametrosModuloCapa.thumbnail;sw_slider(parametrosSlide,callback,timeout)}
if(qtdeFixos>0){swLayoutModuloCapa(param,callback,timeout)}else{param.elemento.querySelector('.p_cont_listagem').remove()}}catch(error){console.error('SW Slide Módulos:',error)}}
function swResetSlideModulos(param){try{if(!param.elemento){throw 'Elemento indefinido'}
const slide=(param.elemento.classList.contains('sw_slider')?param.elemento:param.elemento.querySelector('.sw_slider'));if(slide){sw_slider({elemento:slide,slider:!1})}
const elementoSlide=param.elemento.querySelector('.p_slide');if(elementoSlide){elementoSlide.classList.replace('p_slide','p_cont_listagem')}
const areaSlide=param.elemento.querySelector('.p_area_slide');if(areaSlide){areaSlide.remove()}
if(!param.elemento.querySelector('.p_cont_listagem')){const contListagem=document.createElement('div');contListagem.className='p_cont_listagem p_cont';param.elemento.querySelector('.p_area_listagem').append(contListagem)}}catch(error){console.error('SW Reset Slide Módulos:',error)}}
function swModalCapa(param,callback,timeout){try{if(!param||typeof param!==typeof Object()){throw 'Parâmetros indefinidos.'}else if(typeof param.seletor===typeof undefined){throw 'O parâmetro {param.seletor} (id ou classe) é necessário para fazer distinção entre os modals abertos.'}
let modal=document.querySelector(param.seletor);if(!modal){modal=document.createElement('div');if(param.seletor.slice(0,1)==='#'){modal.id=param.seletor.slice(1)}else{modal.classList.add(param.seletor.slice(1))}
const btnFechar=document.createElement('div');btnFechar.classList.add('sw_btn_fechar');btnFechar.innerHTML='✕';const contModal=document.createElement('div');contModal.classList.add('sw_cont_modal');param.width=(typeof param.width!==typeof undefined)?param.width:1000;contModal.style.maxWidth=param.width+((/^\d+$/.test(param.width))?'px':'');contModal.append(btnFechar);modal.append(contModal);document.body.append(modal)}
if(param.class){modal.className='';modal.classList.add(...param.class.split(' '))}
modal.classList.add('sw_modal_capa');const transicao=window.getComputedStyle(modal).getPropertyValue('transition-duration').replace(/\D/g,"")*10;if(param.titulo){if(modal.querySelector('.sw_titulo_modal')){modal.querySelector('.sw_titulo_modal').remove()}
const tituloModal=document.createElement('div');tituloModal.classList.add('sw_titulo_modal');if(typeof param.titulo===typeof Object()&&param.titulo.length){tituloModal.append(...param.titulo)}else{tituloModal.append(param.titulo)}
modal.querySelector('.sw_cont_modal').append(tituloModal)}
if(param.conteudo){if(modal.querySelector('.sw_conteudo_modal')){modal.querySelector('.sw_conteudo_modal').remove()}
const conteudoModal=document.createElement('div');conteudoModal.classList.add('sw_conteudo_modal');if(typeof param.conteudo===typeof Object()&&param.conteudo.length){conteudoModal.append(...param.conteudo)}else{conteudoModal.append(param.conteudo)}
modal.querySelector('.sw_cont_modal').append(conteudoModal)}
const fecharModal=()=>{modal.classList.remove("show");window.removeEventListener('keydown',fecharModalEsc);document.body.classList.remove('ovfhidden');if(param.remover!==!1){setTimeout(()=>{modal.remove()},transicao)}}
const fecharModalEsc=(e)=>{if(e.keyCode===27||e.key==='Escape'){fecharModal()}}
modal.addEventListener('click',(e)=>{if(!e.target.classList.contains('sw_titulo_modal')&&!e.target.closest('.sw_titulo_modal')&&!e.target.classList.contains('sw_conteudo_modal')&&!e.target.closest('.sw_conteudo_modal')){fecharModal()}});window.addEventListener('keydown',fecharModalEsc);document.body.classList.add('ovfhidden');setTimeout(()=>{document.querySelector('.sw_modal_capa').classList.add('show')});if(callback){timeout=(typeof timeout!==typeof undefined)?timeout:transicao;if(typeof callback==='function'){setTimeout(()=>{callback.call()},timeout)}else if(Array.isArray(callback)){callback.forEach(f=>{setTimeout(()=>{f.call()},timeout)})}}}catch(error){console.error('SW Modal Capa: ',error);return!1}}
let debounceFlutuante;function swFlutuante(param){try{if(typeof param.elemento===typeof undefined||!param.elemento){throw 'Elemento indefinido'}
if(param.parametrosModuloCapa.flutuante&&param.parametrosModuloCapa.flutuante!=='false'){const contModulo=param.elemento.querySelector('.p_conteudo_modulo');if(!contModulo){throw 'Conteúdo do módulo não encontrado'}
param.elemento.classList.add('sw_flutuante',param.parametrosModuloCapa.flutuante);const contFlutuante=document.createElement('div');contFlutuante.classList.add('sw_cont_flutuante');const btnFechar=document.createElement('button');btnFechar.innerHTML='&#10005;';btnFechar.classList.add('sw_btn_fechar','tamanho_fixo');btnFechar.setAttribute('aria-label','fechar');contFlutuante.append(btnFechar);[...contModulo.children].forEach(item=>{contFlutuante.append(item)});contModulo.innerHTML=null;contModulo.append(contFlutuante);const btnFlutuante=document.createElement('div');btnFlutuante.classList.add('sw_btn_flutuante');if(param.parametrosModuloCapa.icone_flutuante){const icone=document.createElement('div');icone.classList.add('sw_icone_btn');icone.innerHTML=`<span class="swfa ${param.parametrosModuloCapa.icone_flutuante}"></span>`;btnFlutuante.append(icone)}
if(param.parametrosModuloCapa.texto_flutuante){const texto=document.createElement('div');texto.classList.add('sw_txt_btn');texto.innerHTML=`<span>${param.parametrosModuloCapa.texto_flutuante}</span>`;btnFlutuante.append(texto)}
contModulo.append(btnFlutuante);const fecharFlutuante=(hide=!1)=>{document.querySelectorAll('.sw_flutuante').forEach(flutuante=>{flutuante.classList.remove('show');if(hide===!0){flutuante.classList.add('hide')}else{flutuante.classList.remove('hide')}})}
const abrirFlutuante=()=>{fecharFlutuante(!0);param.elemento.classList.add('show')}
btnFlutuante.addEventListener('click',abrirFlutuante);btnFechar.addEventListener('click',fecharFlutuante);swExibicaoMobile({elemento:param.elemento,parametrosModuloCapa:param.parametrosModuloCapa,media:window.innerWidth});window.addEventListener('load',()=>{debounceFlutuante=sw_debounce(()=>{const posicionaBotoes=(btn,i)=>{if(i>0){const height=btn.offsetHeight;const novaMargin=(height*(i))+5;btn.style.marginTop=novaMargin+'px'}}
const botoesEsquerda=document.querySelectorAll('.sw_flutuante.esquerda .sw_btn_flutuante');const botoesDireita=document.querySelectorAll('.sw_flutuante.direita .sw_btn_flutuante');botoesEsquerda.forEach((btn,i)=>{posicionaBotoes(btn,i,botoesEsquerda)});botoesDireita.forEach((btn,i)=>{posicionaBotoes(btn,i,botoesDireita)})},0,debounceFlutuante)})}}catch(error){console.error('SW Flutuante:',error)}}
function swSobreporImagem(elemento,parametroSobreporImagem){if(elemento&&(parametroSobreporImagem!==!1&&parametroSobreporImagem!=='false')){elemento.classList.add('sobrepor',parametroSobreporImagem);const areaInfo=elemento.querySelector('[class^="p_area_info_"]');const areaImg=elemento.querySelector('[class^="p_area_img_"]');const contImg=document.createElement('div');contImg.className='p_cont_img';contImg.append(areaImg.querySelector('img'));areaImg.append(contImg);areaImg.append(areaInfo);const calendarioData=elemento.querySelector('.p_calendario_data');if(calendarioData&&window.getComputedStyle(calendarioData).position==='absolute'&&window.getComputedStyle(areaInfo).position!=='relative'){areaImg.append(calendarioData)}}}
function swGetLinksAcessoFacil(menu,parametrosModuloCapa){const links=document.createElement('div');links.classList.add('p_area_links','p_area_listagem');links.append(document.createElement('div'));const contLinks=links.firstChild;const json=getJSON(menu.querySelector('input').value);if(json){const limiteLinks=parametrosModuloCapa.limite_links&&parametrosModuloCapa.limite_links<json.length?parametrosModuloCapa.limite_links-1:json.length;contLinks.classList.add('p_cont','p_cont_listagem');if(parametrosModuloCapa.disposicao_invertida_links){contLinks.classList.add('disposicao_invertida')}
if(parametrosModuloCapa.exibicao_item_link){contLinks.classList.add('exibicao_'+parametrosModuloCapa.exibicao_item_link)}
const linkModelo=(json)=>{const linkAcessoFacil=document.createElement('div');linkAcessoFacil.classList.add('p_link_acesso_facil','p_item');linkAcessoFacil.innerHTML=`
            ${json.link ? `<a href="${json.link}" target="${json.target}">` : ''}
                <div class="p_cont_link_acesso_facil p_cont p_cont_item">
                    <div class="p_area_img_link_acesso_facil p_area_icone_link_acesso_facil p_area_img p_area_icone">
                        <span class="swfa"></span>
                    </div>
                    <div class="p_area_info_link_acesso_facil p_area_info p_cont">
                        <div class="p_titulo">${json.nome}</div>
						${parametrosModuloCapa.texto_links ? `<div class="p_info">${parametrosModuloCapa.texto_links}</div>` : ''}
                        <div class="p_botao"></div>
                    </div>
                </div>
			${json.link ? `</a>` : ''}`;const icone=(json.icone)?json.icone:parametrosModuloCapa.icone_padrao_links;if(icone&&parametrosModuloCapa.icone_links){linkAcessoFacil.querySelector('.swfa').classList.add(...icone.split(' '))}else{linkAcessoFacil.querySelector('.p_area_icone_link_acesso_facil').remove()}
const botao=linkAcessoFacil.querySelector('.p_botao');if(parametrosModuloCapa.botao_links){botao.classList.add('b'+parametrosModuloCapa.botao_links);if(parametrosModuloCapa.icone_botao_links){const iconeBotao=document.createElement('span');iconeBotao.classList.add('swfa',...json.icone.split(' '));botao.append(iconeBotao)}
if(parametrosModuloCapa.texto_botao_links){const iconeBotao=document.createElement('span');iconeBotao.classList.add('p_txt_btn');iconeBotao.innerHTML=parametrosModuloCapa.texto_botao_links;botao.append(iconeBotao)}}else{botao.remove()}
return linkAcessoFacil}
for(let i=0;i<limiteLinks;i++){const linkAcessoFacil=linkModelo(json[i]);if(parametrosModuloCapa.delay_links>0){linkAcessoFacil.classList.add('hide')}
links.firstChild.append(linkAcessoFacil)}
if(limiteLinks<parametrosModuloCapa.limite_links&&parametrosModuloCapa.limite_links<json.length){const linkVerTodos=linkModelo({icone:parametrosModuloCapa.icone_ver_todos,nome:parametrosModuloCapa.titulo_ver_todos,});linkVerTodos.classList.add('p_link_ver_todos')
if(parametrosModuloCapa.delay_links>0){linkVerTodos.classList.add('hide')}
linkVerTodos.addEventListener('click',()=>{const parametrosModal={...parametrosModuloCapa};parametrosModal.exibicao_links='modal';parametrosModal.limite_links=!1;swShowLinksAcessoFacil(menu,parametrosModal,!0)});links.firstChild.append(linkVerTodos)}
const quantidadeLinks=contLinks.querySelectorAll('.p_link_acesso_facil').length;contLinks.classList.add('m'+parametrosModuloCapa.multiplos_links);contLinks.classList.add('lr'+(quantidadeLinks%parametrosModuloCapa.multiplos_links));(quantidadeLinks%2===1)&&contLinks.classList.add('li')}else{const infoModal=document.createElement('div');infoModal.className='p_info_modal';infoModal.innerHTML='<span class="swfa fas fa-exclamation-triangle"></span> Não foi possível listar links para este menu';links.firstChild.append(infoModal)}
return links}
function swShowLinksAcessoFacil(menu,parametrosModuloCapa,capa=!0){const efeitoExibicao=(linksMenu)=>{let timeout=0;linksMenu.querySelectorAll('.hide').forEach(link=>{setTimeout(()=>{link.classList.remove('hide')},timeout+=parametrosModuloCapa.delay_links)})}
if(parametrosModuloCapa.exibicao_links==='dropdown'&&(menu.classList.contains('show')||event.type==='mouseleave')){menu.classList.remove('show')}else{const linksMenu=swGetLinksAcessoFacil(menu,parametrosModuloCapa);if(parametrosModuloCapa.exibicao_links==='modal'){const tituloModal=document.createElement('div');if(menu.querySelector('.p_btn_menu .swfa')){tituloModal.append(menu.querySelector('.p_btn_menu .swfa').cloneNode())}
if(menu.querySelector('.p_btn_menu img')){tituloModal.append(menu.querySelector('.p_btn_menu img').cloneNode())}
const spanTitulo=document.createElement('span');spanTitulo.innerText=menu.querySelector('.p_btn_menu .p_titulo').innerText;tituloModal.append(spanTitulo);const callback=(parametrosModuloCapa.delay_links>0)&&efeitoExibicao(linksMenu);const idAcessoFacil=(menu.getAttribute('data-id'))?menu.getAttribute('data-id'):'';let classeModal='af'+idAcessoFacil;if(capa){classeModal+=' p_area_acesso_facil_capa'}
swModalCapa({seletor:'#p_modal_acesso_facil',titulo:tituloModal.children,class:classeModal,conteudo:linksMenu,},callback)}else if(parametrosModuloCapa.exibicao_links==='dropdown'){const dropdown=document.createElement('div');dropdown.classList.add('p_dropdown','p_dropdown_acesso_facil');if(menu.querySelector('.p_dropdown')){menu.querySelector('.p_dropdown').remove()}
dropdown.append(linksMenu);if(parametrosModuloCapa.delay_links>0){efeitoExibicao(linksMenu)}
menu.append(dropdown);if(event.type==='click'){const click=()=>{if(event.target.closest('.p_menu_acesso_facil')!==menu){menu.classList.remove('show');window.removeEventListener('click',click)}}
window.addEventListener('click',click)}
setTimeout(()=>{menu.classList.add('show')},10)}else{console.error('Não foi possível identificar o parâmetro "exibicao_links".')}}}
function swAcessoFacil(menu,parametrosModuloCapa,capa){if(parametrosModuloCapa.acesso_facil==='lista'||parametrosModuloCapa.exibicao_links==='lista'){const lista=document.createElement('div');lista.classList.add('p_lista','p_lista_acesso_facil');lista.append(swGetLinksAcessoFacil(menu,parametrosModuloCapa));menu.append(lista)}else{if(parametrosModuloCapa.abrir_clique||window.innerWidth<1000){menu.addEventListener('click',()=>{swShowLinksAcessoFacil(menu,parametrosModuloCapa,capa)})}else{menu.addEventListener('mouseenter',()=>{swShowLinksAcessoFacil(menu,parametrosModuloCapa,capa)});menu.addEventListener('mouseleave',()=>{swShowLinksAcessoFacil(menu,parametrosModuloCapa,capa)})}}}
function swVotarEnquete(enquete){try{if(!enquete){throw 'Elemento da enquete não identificado'}
enquete.querySelector('form').addEventListener('submit',(e)=>{e.preventDefault();const form=e.target;enquete.querySelector('button').disabled=!0;try{if(!form.querySelector('input[type="radio"]:checked')){throw{mensagem:'Selecione uma resposta'}}
for(const input of form.querySelectorAll('.p_area_validacao input')){if(!input.value){throw{mensagem:`Preencha o campo: ${input.getAttribute('placeholder')}`,callback:()=>{input.focus()}}}else if(input.getAttribute('name')==='form_cpf'&&!validarCPF(input.value)){throw{mensagem:`CPF inválido`,callback:()=>{input.focus()}}}}
const captcha=enquete.querySelector('textarea.g-recaptcha-response').value;if(!captcha){throw{mensagem:'Preencha o desafio "Não sou um robô"'}}
const dados=new FormData(form);dados.append('captcha',captcha);dados.append('enviar','s');fetch('/portal/enquete/votar/',{method:'POST',body:dados}).then(function(response){return response.text()}).then(function(data){enquete.querySelector('.p_cont_enquete').replaceChildren();const retorno=document.createElement('div');retorno.innerHTML=data;Array.from(retorno.children).forEach(elemento=>{if(elemento.tagName.toLocaleLowerCase()==='script'){const script=document.createElement('script');script.innerHTML=elemento.innerText;enquete.querySelector('.p_cont_enquete').append(script)}else{enquete.querySelector('.p_cont_enquete').append(elemento)}})})}catch(error){if(!error.mensagem){error.mensagem='Algo errado aconteceu...';console.error(error)}
swal({text:error.mensagem,icon:'warning'}).then(()=>{if(error.callback){error.callback.call()}});enquete.querySelector('button').disabled=!1}})}catch(error){console.error('SW Votar Enquete',error)}}